version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
      PORT: 5000
    entrypoint: npm run start
    ports:
      - "3000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data: